# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-check:
    runs-on: ${{ matrix.os }}
    strategy:
      # Default is true, cancels jobs for other platforms in the matrix if one fails
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        go-version:
          - "1.25"

        include:
          - os: ubuntu-latest
            urlTemplate: "https://github.com/caddyserver/xcaddy/releases/download/{{version}}/xcaddy_{{rawVersion}}_linux_amd64.tar.gz"
            name: "xcaddy"
            pathInArchive: "xcaddy"

          - os: "macos-latest"
            urlTemplate: "https://github.com/caddyserver/xcaddy/releases/download/{{version}}/xcaddy_{{rawVersion}}_mac_amd64.tar.gz"
            name: "xcaddy"
            pathInArchive: "xcaddy"

          - os: "windows-latest"
            urlTemplate: "https://github.com/caddyserver/xcaddy/releases/download/{{version}}/xcaddy_{{rawVersion}}_windows_amd64.zip"
            name: "xcaddy.exe"
            pathInArchive: "xcaddy.exe"

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        check-latest: true
        cache: true
        go-version: ${{ matrix.go-version }}

    - name: Set up xcaddy
      uses: engineerd/configurator@v0.0.10
      with:
        name: ${{ matrix.name }}
        pathInArchive: ${{ matrix.pathInArchive }}
        fromGitHubReleases: "true"
        repo: "caddyserver/xcaddy"
        version: "latest"
        urlTemplate: ${{ matrix.urlTemplate }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        xcaddy build master --output ${{ runner.temp }}/${{ matrix.name }} --with github.com/mholt/caddy-l4=./
        # smoking test
        echo ''
        echo '########'
        echo "# ${{ runner.temp }}/${{ matrix.name }} version"
        ${{ runner.temp }}/${{ matrix.name }} version
        echo '########'
        echo ''
        echo '########'
        echo "# ${{ runner.temp }}/${{ matrix.name }} list-modules"
        ${{ runner.temp }}/${{ matrix.name }} list-modules
        echo '########'
        echo ''
        echo '########'
        echo "# ${{ runner.temp }}/${{ matrix.name }} build-info"
        ${{ runner.temp }}/${{ matrix.name }} build-info
        echo '########'

    - name: Test
      run: |
        # TODO:
        # github.com/mholt/caddy-l4,
        # modules/l4echo,
        # modules/l4postgres,
        # modules/l4ssh,
        # modules/l4subroute,
        # modules/l4tee,
        # modules/l4throttle,
        # modules/l4tls,
        # modules/l4xmpp needs their test files.

        go test -v ./...
